name: Run Makefile and execute output

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++-13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install g++-13 -y

      - name: Set g++ version to 13
        run: |
          sudo apt-get remove g++-11 -y
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Execute output and check result
        run: ./scripts/test.sh
