name: Run Makefile and execute output

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute output and check result
        run: ./scripts/test.sh
